### ISSUE TITLE
GvNix Typical security & “web mvc batch setup” incompatible?

### ISSUE THREAD

**Issue by Forgev41** [gvSIGAssociation/gvnix#15]
One of the best features of GvNix is “Typical security”.

This feature works great but breaks when using togehter with the “web mvc batch setup” feature.

As the testcase I used the Quickstart.roo script from https://github.com/DISID/gvnix-samples/blob/master/quickstart-app/quickstart.roo

The only thing I changed in the script was replacing “security setup” by “typicalsecurity setup”. I tested it and finally found that as long as I do not use the “web mvc batch setup” feature everything works fine.

More info see issue at StackOverflow: https://stackoverflow.com/questions/32186006/gvnix-typical-security-web-mvc-batch-setup-incompatible

**Comment by jcagarcia** [comment]
Hi @Forgev41,

I'll keep this issue in mind for future versions of gvNIX.

Best Regards and thanks for your interest and contribution to gvNIX project.

**Comment by jcagarcia** [comment]
Hi again @Forgev41 ,

Problems related with typical security and batch operations have been solved on new gvNIX 1.5.1.RC1

You can download it from http://www.gvnix.org.

Any feedback will be appreciated!

Regards,
