### ISSUE TITLE
Petclinic does not resolve dependencies

### ISSUE THREAD

**Issue by jaimemm** [gvSIGAssociation/gvnix#18]
Hi,

When using both GVNIX 2.0.0M1 or 1.5.0 RELEASE, petclinic sample does not build due to non resolved dependencias (it might be they are too old...). Here's the list of the dependencies which are not  resolved by maven: 

[WARNING] The POM for org.springframework.roo.wrapping:org.springframework.roo.wrapping.inflector:jar:0.7.0.0010 is missing, no dependency information available
[WARNING] The POM for org.springframework.roo.wrapping:org.springframework.roo.wrapping.hapax:jar:2.3.4.0010 is missing, no dependency information available
[WARNING] The POM for org.springframework.uaa:org.springframework.uaa.client:jar:1.0.2.RELEASE is missing, no dependency information available
[WARNING] The POM for com.github.dandelion:datatables-core:jar:0.9.3-GVNIX is missing, no dependency information available
[WARNING] The POM for com.github.dandelion:datatables-jsp:jar:0.9.3-GVNIX is missing, no dependency information available
[WARNING] The POM for com.github.dandelion:datatables-servlet2:jar:0.9.3-GVNIX is missing, no dependency information available
[WARNING] The POM for com.github.dandelion:datatables-export-itext:jar:0.9.3-GVNIX is missing, no dependency information available
[WARNING] The POM for com.github.dandelion:datatables-export-poi:jar:0.9.3-GVNIX is missing, no dependency information available
[WARNING] The POM for com.github.dandelion:datatables-export-poi-ooxml:jar:0.9.3-GVNIX is missing, no dependency information available
[WARNING] The POM for com.github.dandelion:datatables-spring3:jar:0.9.3-GVNIX is missing, no dependency information available
[WARNING] The POM for com.vividsolutions:jts:jar:1.10 is missing, no dependency information available
[WARNING] The POM for org.hibernate:hibernate-spatial:jar:4.3 is missing, no dependency information available
[WARNING] The POM for com.lowagie:itext:jar:2.1.7.js1 is missing, no dependency information available
[WARNING] The POM for org.springframework.roo.wrapping:org.springframework.roo.wrapping.antlr4-runtime:jar:4.3.0002 is missing, no dependency information available

How could it be fixed (updating pom files or adding new repos to our nexus)?

Regards

**Comment by frnore** [comment]
Hi @jaimemm , 

We could not reproduce your issue with both gvNIX 2.0.0.M1 or gvNIX 1.5.0.RELEASE.
We've tried to generate and build a quickstart sample app (https://github.com/DISID/gvnix-samples/blob/master/quickstart-app/quickstart.roo)  with both gvNIX versions and all dependencies downloaded successful.

Here is the output when downloaded datatables-core-0.9.3-GVNIX.pom; 

````
Downloading: http://maven.springframework.org/release/com/github/dandelion/datatables-core/0.9.3-GVNIX/datatables-core-0.9.3-GVNIX.pom
Downloading: http://maven.springframework.org/milestone/com/github/dandelion/datatables-core/0.9.3-GVNIX/datatables-core-0.9.3-GVNIX.pom
Downloading: http://spring-roo-repository.springsource.org/release/com/github/dandelion/datatables-core/0.9.3-GVNIX/datatables-core-0.9.3-GVNIX.pom
Downloading: http://repository.gvnix.org/com/github/dandelion/datatables-core/0.9.3-GVNIX/datatables-core-0.9.3-GVNIX.pom
Downloaded: http://repository.gvnix.org/com/github/dandelion/datatables-core/0.9.3-GVNIX/datatables-core-0.9.3-GVNIX.pom (3 KB at 5.7 KB/sec)
````

Please, try again to build your project with Maven debug mode to see the full execution output. You can use the following command: 
mvn clean compile -X

Best regards.

**Comment by jaimemm** [comment]
Hi,

That might be caused because you have the dependencies into your nexus, because they are definitely not present in mavenrepository.com. Which repository do you use to load the 0.9.3-GVNIX

Regards

**Comment by frnore** [comment]
Hi @jaimemm , 

We're using our own repository (http://repository.gvnix.org) to download Dandelion dependencies such as datatables-core:jar:0.9.3-GVNIX.

The file pom.xml of your gvNIX project must have included this repository:
````
    <repository>
            <id>gvNIX External Libraries repo</id>
            <url>http://repository.gvnix.org</url>
            <name>gvNIX External Libraries repo</name>
        </repository>
````

By the way, If you are using gvNIX 1.5.0.RELEASE or gvNIX 2.0.0.M, this repository should be included by default...

Regards,

**Comment by jaimemm** [comment]
Sorted! Thanks a lot!

**Comment by frnore** [comment]
Thanks for contribute to gvNIX project!!

Best Regards,
