### ISSUE TITLE
Selenium tests fail on geo-gvnix.rhcloud.com

### ISSUE THREAD

**Issue by tullo** [gvSIGAssociation/gvnix#2]
The selenium configuration currently uses a hardcoded value 'localhost' for the hostname in the URL.

Should probably be made configurable via profiles or just a simple property
```
...
<properties>
   <hostname>geo-gvnix.rhcloud.com</hostname>
</properties>
...
```
http://geo-gvnix.rhcloud.com/resources/selenium/test-suite.xhtml

**Comment by jcagarcia** [comment]
We just updated selenium hostname on sample applications.

Best Regards,
