### ISSUE TITLE
Undo manage webmvc-config.xml Can't get Type details

### ISSUE THREAD

**Issue by arielt1985** [gvSIGAssociation/gvnix#20]
Using gvNIX 1.5.

Tried to use gvNIX to create datatables for my domain model. Followed the quickstart on github, with modifications for my problem domain. Everything runs OK until I get to:

`~.domain.Profile roo-gvNIX> web mvc datatables add --type ~.web.Profile --inline true --ajax true`
Which results in:

`Undo manage SRC_MAIN_WEBAPP/WEB-INF/spring/webmvc-config.xml`
`Can't get Type details`
What is the meaning of the "Undo manage" message? Anything else I can investigate?

**Comment by jcagarcia** [comment]
Hi @arielt1985 

Could you provide us your **log.roo** script to be able to check your issue?

Regards,

**Comment by arielt1985** [comment]
Here it is:
`
// Spring Roo 1.3.2.RELEASE [rev 8c2549b] log opened at 2015-10-15 09:05:36
project --topLevelPackage com.project --projectName lccr
jpa setup --provider HIBERNATE --database HYPERSONIC_PERSISTENT
entity jpa --class ~.domain.CSP
entity jpa --class ~.domain.Target
entity jpa --class ~.domain.Customer
entity jpa --class ~.domain.Contract
entity jpa --class ~.domain.DemandProfile
field string --fieldName name --notNull --sizeMin 3 --sizeMax 30 --class ~.domain.CSP
field reference --fieldName targets --type ~.domain.Target
field reference --fieldName contracts --type ~.domain.Contract
field string --fieldName userName --notNull --sizeMin 3 --sizeMax 256 --class ~.domain.Target
field string --fieldName userPassword --notNull --sizeMin 3 --sizeMax 256
field string --fieldName address --notNull --sizeMin 3 --sizeMax 256
field set --fieldName csp --type ~.domain.CSP --notNull --cardinality ONE_TO_MANY --mappedBy targets
field number --fieldName discount --type float --class ~.domain.Contract
field set --fieldName csp --type ~.domain.CSP --notNull --cardinality ONE_TO_MANY --mappedBy contracts
field set --fieldName customer --type ~.domain.Customer --notNull --cardinality ONE_TO_MANY --mappedBy contracts
field string --fieldName name --notNull --sizeMin 3 --sizeMax 256 --class ~.domain.Customer
field reference --fieldName contracts --type ~.domain.Contract
field number --fieldName fld1 --type float --class ~.domain.DemandProfile
field number --fieldName fl2 --type float
web mvc setup
web mvc all --package ~.web
web mvc jquery setup
web mvc jquery all
web mvc datatables setup
web mvc bootstrap setup
jpa gvnix setup
jpa batch all
web mvc batch setup
web mvc batch all
// [failed] web mvc datatables add --type ~.web.DemandProfile --inline true --ajax true
// [failed] web mvc datatables add --type ~.web.Contract --inline true --ajax true
// [failed] web mvc datatables add --type ~.web.Target --inline true --ajax true
exit
// Spring Roo 1.3.2.RELEASE [rev 8c2549b] log closed at 2015-10-15 09:10:43
`

**Comment by jcagarcia** [comment]
Hi @arielt1985 

You should specify a valid controller class on --type attribute. You are using ~.web.DemandProfile but that class doesn't exist on your generated project.

The correct commands to use are:
````
web mvc datatables add --type ~.web.DemandProfileController --inline true --ajax true
web mvc datatables add --type ~.web.ContractController --inline true --ajax true
web mvc datatables add --type ~.web.TargetController --inline true --ajax true
````

I suggest you that use _autocomplete_ gvNIX feature using TAB if you are using gvNIX on your system shell or CTRL + Space if you are using gvNIX on STS IDE.

Hope this help.

Best Regards,

**Comment by arielt1985** [comment]
Thank you! I'll give that a try.
