### ISSUE TITLE
Problem with loupe field

### ISSUE THREAD

**Issue by marcocaimi** [gvSIGAssociation/gvnix#5]
Hi, i created a loupe field on a ajax data table. When i enter the edit state for a row the loupe field is not preloaded with the correct value and if i modify another filed on the row i cannot commit the update because the loupe if field is effectively set to null...What else should ai do to make loupe field work?

**Comment by jcagarcia** [comment]
Hi marcoaimi, 

Could you provide us the .roo file that includes executed commands?

Regards,

**Comment by marcocaimi** [comment]
this is the .roo file:

// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-11 10:27:57
project --topLevelPackage it.digitelematica.leovince --projectName ordersmanager
jpa setup --provider HIBERNATE --database POSTGRES 
entity jpa --class ~.domain.Product 
finder add --finderName findOrdersRowByProduct
finder list
finder add --finderName findOrderRowsByProduct
finder list
finder add --finderName findOrderRowsByProduct --class ~.domain.OrderRow
finder add --finderName findOrderRowsByHeader --class ~.domain.OrderRow
web mvc setup
web mvc all --package ~.web
web mvc finder all
web mvc language it
web mvc language en
web mvc jquery setup
web mvc jquery all
web mvc datatables setup 
web mvc bootstrap setup
jpa gvnix setup 
jpa batch all
web mvc batch setup
web mvc batch all
web mvc datatables add --type ~.web.OrderRowController --inline true --ajax true
web mvc datatables add --type ~.web.OrderHeaderController
web mvc datatables detail add --type ~.web.OrderHeaderController --property orderRows
exit
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log closed at 2015-02-11 10:36:42
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-11 10:42:26
web mvc loupe setup
menu setup
security setup
web mvc bootstrap update
exit
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log closed at 2015-02-11 10:49:25
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-11 10:55:01
exit
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log closed at 2015-02-11 10:55:19
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-11 10:55:26
web mvc datatables all 
web mvc jquery update tags
web mvc bootstrap update
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-11 11:18:51
web mvc bootstrap update
web mvc bootstrap update
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-11 13:33:01
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log closed at 2015-02-11 15:23:36
web mvc loupe field --controller ~.web.AppUserController --field customer
web mvc loupe set --controller ~.web.AppUserController
web mvc datatables add --type ~.web.AppRoleController --ajax true --inline true --mode show
web mvc datatables add --type ~.web.AppRoleController --ajax true --inline true --mode show
quit
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log closed at 2015-02-12 11:22:56
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-12 18:24:58
exit
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log closed at 2015-02-12 18:32:09
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-13 12:22:03
pgp trust --keyId 0xBF0451C0
hint
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log closed at 2015-02-13 15:24:23
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-16 11:23:51
web mvc datatables add --type ~.web.ForecastRowController --ajax true --inline true --mode show
web mvc datatables add --type ~.web.ForecastHeaderController
web mvc datatables add --type ~.web.ForecastHeaderController --ajax true
// [failed] web mvc datatables detail add --type ~.web.ForecastHeaderController --property orderRows
web mvc datatables detail add --type ~.web.ForecastHeaderController --property forecastRows
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-20 10:56:39
field string --fieldName cap --class it.digitelematica.leovince.domain.Customer
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log closed at 2015-02-20 12:19:41
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-20 15:12:40
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-02-27 10:55:03
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log closed at 2015-02-27 18:03:00
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-03-02 11:31:40
// Spring Roo 1.3.0.RELEASE [rev 4877cfb] log opened at 2015-03-04 13:06:50

**Comment by marcocaimi** [comment]
you can try the live application at:
http://svr12.digitelematica.org/ordersmanager/
user: admin
pwd: admin

then go to Administration -> list all users
there you find a loupe field on the Customer column that does not work

**Comment by jcagarcia** [comment]
Could you try to execute the same script with gvNIX 1.3.1.RELEASE, gvNIX 1.4.0.RELEASE or gvNIX 1.4.1.RELEASE?

http://sourceforge.net/projects/gvnix/files/gvNIX-1.3.1-RELEASE.zip/download
http://sourceforge.net/projects/gvnix/files/gvNIX-1.4.0.RELEASE.zip/download
http://sourceforge.net/projects/gvnix/files/gvNIX-1.4.1.RELEASE.zip/download

**Comment by marcocaimi** [comment]
This was executed with gvNIX 1.4.0.RELEASE

**Comment by marcocaimi** [comment]
I'm trying to debug  the javascript methods which draw the loupe field when in edit mode which i suppose should set the id of the current value in the hidden input field but i don't find anything similar there. Nor my callback function is never called....

**Comment by marcocaimi** [comment]
Hi, i tried the gvnix quikstart app on line. The loupe fields are not working even there....I downloaded the code and compiled with mvn but in the donloadable version there is no trace of loupe fields....is it possible to have some documentation on those features? Can someone help us when is not occupied with Las Fallas? (:-))..Thank you.

**Comment by jcagarcia** [comment]
Hi marcocalmi, we're working on your issue... i'll notice you when we have some solution to this issue... Regards

**Comment by jcagarcia** [comment]
Hi marcocalmi, there was an issue on *loupe.tagx* file.

You can edit *loupe.tagx* file at line *155* modifying the current code:

`<c:when test="${!disableFormBinding}">`

with this one:

`<c:when test="${disableFormBinding}">`

Could you notice me when you apply this changes?

Regards,

**Comment by jcagarcia** [comment]
Hi again,

Your problem was solved on the following commit https://github.com/gvSIGAssociation/gvnix/commit/82d4431185a88992d4394ad9429d412dcc8a5697

Regards,

**Comment by RRVishwakarma** [comment]
why datatable or inline editing not working in my gvnix  project petclinic

**Comment by RRVishwakarma** [comment]
I am using 1.5 gvnix
